In [1]:
from bs4 import BeautifulSoup
import requests

In [2]:
html_doc = requests.get('https://www.worldometers.info/coronavirus/')

In [3]:
soup = BeautifulSoup(html_doc.text, 'html')

In [4]:
# print(soup.prettify())

In [5]:
table_content = soup.find('table')

In [31]:
table_head = table_content.find('thead')
table_body = table_content.find('tbody')
table_row = table_body.find_all('tr')
for data in table_row[8:]:
    # print(table_row)
    # print("--------------------------------------------------------------------------------------")
    pass

In [33]:
import csv
with open('output_table.csv', mode='w', encoding = 'utf-8') as file:
    writer = csv.writer(file)
    header_data = []
    for th in table_head.find_all('th'):
        header_data.append(th.text.strip())
    writer.writerow(header_data)
        
    for row in table_row[8:]:
        row_data = []
        for td in row.find_all(['td']):
            row_data.append(td.text.strip())
        writer.writerow(row_data)

print("Data successfully written to 'output_table.csv'")

Data successfully written to 'output_table.csv'

In [48]:
import pandas as pd
df = pd.read_csv('output_table.csv')
df

       #   Country,Other   TotalCases  ...  New Cases/1M pop New Deaths/1M pop  Active Cases/1M pop
0      1             USA  111,820,082  ...               NaN               NaN                2,348
1      2           India   45,035,393  ...               NaN               NaN                  0.4
2      3          France   40,138,560  ...               NaN               NaN                  NaN
3      4         Germany   38,828,995  ...               NaN               NaN                4,833
4      5          Brazil   38,743,918  ...               NaN               NaN                8,281
..   ...             ...          ...  ...               ...               ...                  ...
226  227         Tokelau           80  ...               NaN               NaN               58,055
227  228    Vatican City           29  ...               NaN               NaN                  NaN
228  229  Western Sahara           10  ...               NaN               NaN                  NaN
229  230      MS Zaandam            9  ...               NaN               NaN                  NaN
230  231           China      503,302  ...               NaN               NaN                   82

[231 rows x 22 columns]

In [49]:
df['TotalTests'].value_counts()

TotalTests
78,646           2
1,186,851,502    1
1,690,934        1
98,964           1
1,048,704        1
                ..
7,885,792        1
45,481,735       1
2,657,506        1
7,748,050        1
160,000,000      1
Name: count, Length: 212, dtype: int64

In [56]:
df

       #   Country,Other   TotalCases  ...  New Cases/1M pop New Deaths/1M pop  Active Cases/1M pop
0      1             USA  111,820,082  ...               NaN               NaN                2,348
1      2           India   45,035,393  ...               NaN               NaN                  0.4
2      3          France   40,138,560  ...               NaN               NaN                  NaN
3      4         Germany   38,828,995  ...               NaN               NaN                4,833
4      5          Brazil   38,743,918  ...               NaN               NaN                8,281
..   ...             ...          ...  ...               ...               ...                  ...
226  227         Tokelau           80  ...               NaN               NaN               58,055
227  228    Vatican City           29  ...               NaN               NaN                  NaN
228  229  Western Sahara           10  ...               NaN               NaN                  NaN
229  230      MS Zaandam            9  ...               NaN               NaN                  NaN
230  231           China      503,302  ...               NaN               NaN                   82

[231 rows x 22 columns]

In [65]:
active = df[df.ActiveCases == "0"]

In [66]:
active

       #          Country,Other  TotalCases  ...  New Cases/1M pop New Deaths/1M pop  Active Cases/1M pop
2      3                 France  40,138,560  ...               NaN               NaN                  NaN
5      6               S. Korea  34,571,873  ...               NaN               NaN                  NaN
8      9                     UK  24,910,387  ...               NaN               NaN                  NaN
14    15                 Taiwan  10,241,523  ...               NaN               NaN                  NaN
25    26                Ukraine   5,557,995  ...               NaN               NaN                  NaN
31    32                   DPRK   4,772,813  ...               NaN               NaN                  NaN
34    35                   Peru   4,572,667  ...               NaN               NaN                  NaN
39    40                Denmark   3,183,756  ...               NaN               NaN                  NaN
40    41              Singapore   3,006,155  ...               NaN               NaN                  NaN
48    49               Slovakia   1,877,605  ...               NaN               NaN                  NaN
54    55                 Norway   1,509,732  ...               NaN               NaN                  NaN
67    68                Ecuador   1,070,188  ...               NaN               NaN                  NaN
71    72               Mongolia   1,011,496  ...               NaN               NaN                  NaN
79    80                 Cyprus     681,110  ...               NaN               NaN                  NaN
144  145                  Sudan      63,993  ...               NaN               NaN                  NaN
147  148                  Syria      57,743  ...               NaN               NaN                  NaN
149  150             Seychelles      51,220  ...               NaN               NaN                  NaN
167  168            Saint Lucia      30,215  ...               NaN               NaN                  NaN
188  189       Marshall Islands      16,138  ...               NaN               NaN                  NaN
189  190               Dominica      16,038  ...               NaN               NaN                  NaN
199  200                Eritrea      10,189  ...               NaN               NaN                  NaN
212  213  Saint Kitts and Nevis       6,607  ...               NaN               NaN                  NaN
222  223       Falkland Islands       1,930  ...               NaN               NaN                  NaN
225  226       Diamond Princess         712  ...               NaN               NaN                  NaN
227  228           Vatican City          29  ...               NaN               NaN                  NaN
228  229         Western Sahara          10  ...               NaN               NaN                  NaN
229  230             MS Zaandam           9  ...               NaN               NaN                  NaN

[27 rows x 22 columns]

In [59]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 231 entries, 0 to 230
Data columns (total 22 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   #                    231 non-null    int64
 1   Country,Other        231 non-null    object
 2   TotalCases           231 non-null    object
 3   NewCases             0 non-null      float64
 4   TotalDeaths          226 non-null    object
 5   NewDeaths            0 non-null      float64
 6   TotalRecovered       183 non-null    object
 7   NewRecovered         5 non-null      float64
 8   ActiveCases          184 non-null    object
 9   Serious,Critical     52 non-null     float64
 10  Tot Cases/1M pop     229 non-null    object
 11  Deaths/1M pop        224 non-null    object
 12  TotalTests           213 non-null    object
 13  Tests/
1M pop       213 non-null    object
 14  Population           229 non-null    object
 15  Continent            229 non-null    object
 16  1 Caseevery X ppl    229 non-null    object
 17  1 Deathevery X ppl   224 non-null    object
 18  1 Testevery X ppl    213 non-null    float64
 19  New Cases/1M pop     0 non-null      float64
 20  New Deaths/1M pop    0 non-null      float64
 21  Active Cases/1M pop  203 non-null    object
dtypes: float64(7), int64(1), object(14)
memory usage: 39.8+ KB

In [115]:
df[df['Country,Other'].str.contains('z') & df['Country,Other'].str.contains('u')]

       # Country,Other TotalCases  NewCases  ... 1 Testevery X ppl  New Cases/1M pop New Deaths/1M pop  Active Cases/1M pop
87    88     Venezuela    552,695       NaN  ...               9.0               NaN               NaN                   10
110  111    Mozambique    233,731       NaN  ...              24.0               NaN               NaN                   81

[2 rows x 22 columns]