In [19]:
import pandas as pd
from dateutil.parser import parse

In [2]:
data = {'ID': ['Eth - 101', 'Eth – 102', 'Eth - 103', 'Eth - 104', 'Eth - 105'], 
        'Name': [' Haileslassie Zeferu Abel', ' Worku Abenezer Girma', ' Abenezer Reta Tamirat', ' Abraham Melisew Fireda', ' Hailu Abraham Niguse'], 
        'Age': [25, None, 29, 33, None], 
        'Salary': [55000, 48000, None, 62000, None]} 
df = pd.DataFrame(data) 
df

          ID                       Name   Age   Salary
0  Eth - 101   Haileslassie Zeferu Abel  25.0  55000.0
1  Eth – 102       Worku Abenezer Girma   NaN  48000.0
2  Eth - 103      Abenezer Reta Tamirat  29.0      NaN
3  Eth - 104     Abraham Melisew Fireda  33.0  62000.0
4  Eth - 105       Hailu Abraham Niguse   NaN      NaN

In [3]:
df_cleaned = df.dropna() 
print(df_cleaned)

          ID                       Name   Age   Salary
0  Eth - 101   Haileslassie Zeferu Abel  25.0  55000.0
3  Eth - 104     Abraham Melisew Fireda  33.0  62000.0

In [5]:
for column in df.columns:
    if df[column].dtype == 'float64' or df[column].dtype == 'int64': 
        df[column].fillna(df[column].mean(), inplace = True)
df

C:\Users\kalki\AppData\Local\Temp\ipykernel_69576\2120743507.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[column].fillna(df[column].mean(), inplace = True)

          ID                       Name   Age   Salary
0  Eth - 101   Haileslassie Zeferu Abel  25.0  55000.0
1  Eth – 102       Worku Abenezer Girma  29.0  48000.0
2  Eth - 103      Abenezer Reta Tamirat  29.0  55000.0
3  Eth - 104     Abraham Melisew Fireda  33.0  62000.0
4  Eth - 105       Hailu Abraham Niguse  29.0  55000.0

In [15]:
for column in df.columns: 
    if df[column].isnull().any(): 
        df[f'{column}_Flag'] = df[column].isna().apply(lambda x: 'Missing' 
    if x else 'Not Missing') 
        # Create a row-based flag 
    df['Missing_Flag'] = df.isnull().any(axis=1).apply(lambda x: 'Missing' if x else 'Not Missing') 
df

          ID                       Name   Age   Salary Missing_Flag
0  Eth - 101   Haileslassie Zeferu Abel  25.0  55000.0  Not Missing
1  Eth – 102       Worku Abenezer Girma  29.0  48000.0  Not Missing
2  Eth - 103      Abenezer Reta Tamirat  29.0  55000.0  Not Missing
3  Eth - 104     Abraham Melisew Fireda  33.0  62000.0  Not Missing
4  Eth - 105       Hailu Abraham Niguse  29.0  55000.0  Not Missing

In [16]:
data = {'ID': ['Eth - 101', 'Eth - 102', 'Eth - 103', 'Eth - 104', 'Eth - 105', 'Eth - 102', 'Eth - 104', 'Eth - 106'], 
        'Name': ['Haileslassie Zeferu Abel', 'Worku Abenezer Girma', 'Abenezer Reta Tamirat', 'Abraham Melisew Fireda', 'Hailu Abraham Niguse', 'Worku Abenezer Girma', 'Abraham Melisew Fireda', 'Hailu Abraham Niguse'], 
        'Age': [25, 29, 29, 33, 29, 29, 33, 29], 
        'Salary': [55000, 48000, 55000, 62000, 55000, 48000, 62000, 55000], 
        'City': ['Addis Ababa', 'Adama', 'Addis Ababa', 'Adama', 'Addis Ababa', 'Adama', 'Adama', 'Addis Ababa']} 
# Original Dataset 
df = pd.DataFrame(data) 
print("Original Dataset") 
print(df, '\n')

Original Dataset
          ID                      Name  Age  Salary         City
0  Eth - 101  Haileslassie Zeferu Abel   25   55000  Addis Ababa
1  Eth - 102      Worku Abenezer Girma   29   48000        Adama
2  Eth - 103     Abenezer Reta Tamirat   29   55000  Addis Ababa
3  Eth - 104    Abraham Melisew Fireda   33   62000        Adama
4  Eth - 105      Hailu Abraham Niguse   29   55000  Addis Ababa
5  Eth - 102      Worku Abenezer Girma   29   48000        Adama
6  Eth - 104    Abraham Melisew Fireda   33   62000        Adama
7  Eth - 106      Hailu Abraham Niguse   29   55000  Addis Ababa

In [17]:
# Exact Match - based on all columns 
df_cleaned = df.drop_duplicates() 
print("Duplicates Removed - Exact Match") 
print(df_cleaned, '\n')

Duplicates Removed - Exact Match
          ID                      Name  Age  Salary         City
0  Eth - 101  Haileslassie Zeferu Abel   25   55000  Addis Ababa
1  Eth - 102      Worku Abenezer Girma   29   48000        Adama
2  Eth - 103     Abenezer Reta Tamirat   29   55000  Addis Ababa
3  Eth - 104    Abraham Melisew Fireda   33   62000        Adama
4  Eth - 105      Hailu Abraham Niguse   29   55000  Addis Ababa
7  Eth - 106      Hailu Abraham Niguse   29   55000  Addis Ababa

In [18]:
# Partial Match - based on specific columns only (e.g., 'ID') 
df_cleaned_id = df.drop_duplicates(subset=['ID']) 
print("Duplicates Removed - Partial Match based on ID") 
print(df_cleaned_id, '\n')

Duplicates Removed - Partial Match based on ID
          ID                      Name  Age  Salary         City
0  Eth - 101  Haileslassie Zeferu Abel   25   55000  Addis Ababa
1  Eth - 102      Worku Abenezer Girma   29   48000        Adama
2  Eth - 103     Abenezer Reta Tamirat   29   55000  Addis Ababa
3  Eth - 104    Abraham Melisew Fireda   33   62000        Adama
4  Eth - 105      Hailu Abraham Niguse   29   55000  Addis Ababa
7  Eth - 106      Hailu Abraham Niguse   29   55000  Addis Ababa

In [20]:
data = { 
    'Event ID': ['E-001', 'E-002', 'E-003', 'E-004', 'E-005'], 
    'Event Date': ['01/12/2023', 'December 2, 2023', '2023-12-03', '12.04.2023', '5th Dec 2023'], 
    'Product Name': ['apple', 'Banana', 'ORANGE', 'BaNAna', 'Apple'], 
    'Weight' : ['70 kg', '100 lbs', '88 KG', '180 pound', '94 kilograms'] 
} 
df = pd.DataFrame(data) 
print("Original Dataset") 
print(df, '\n')

Original Dataset
  Event ID        Event Date Product Name        Weight
0    E-001        01/12/2023        apple         70 kg
1    E-002  December 2, 2023       Banana       100 lbs
2    E-003        2023-12-03       ORANGE         88 KG
3    E-004        12.04.2023       BaNAna     180 pound
4    E-005      5th Dec 2023        Apple  94 kilograms

In [23]:
def parse_date(date_str): 
    try: 
        return parse(date_str, dayfirst=False) 
    except ValueError: 
        return pd.NaT 
df['Event Date'] = df['Event Date'].apply(parse_date) 
df['Event Date'] = df['Event Date'].dt.strftime('%d-%m-%y') 
print("Result") 
print(df)

Result
  Event ID Event Date Product Name        Weight
0    E-001   01-12-12        apple         70 kg
1    E-002   12-02-02       Banana       100 lbs
2    E-003   12-03-03       ORANGE         88 KG
3    E-004   12-04-04       BaNAna     180 pound
4    E-005   12-05-05        Apple  94 kilograms

In [26]:
df = pd.DataFrame(data) 
# Extract numeric value and unit 
df['Numeric Value'] = df['Weight'].str.extract(r'(\d+\.?\d*)').astype(float
) 
# Use str to convert the extracted unit to lowercase 
df['Unit'] = df['Weight'].str.extract(r'([a-zA-Z]+)')[0].str.lower() # Access the first element of the returned DataFrame, which is a Series 
# Conversion function 
def convert_to_kg(row): 
    if row['Unit'] in ['kg', 'kilograms']: 
        return row['Numeric Value'] 
    elif row['Unit'] in ['lbs', 'pound']: 
        return row['Numeric Value'] * 0.453592 
    else: 
        return None  # or handle unknown units 
df['Weight in kg'] = df.apply(convert_to_kg, axis=1) 
print(df[['Event ID', 'Weight', 'Weight in kg']])

  Event ID        Weight  Weight in kg
0    E-001         70 kg      70.00000
1    E-002       100 lbs      45.35920
2    E-003         88 KG      88.00000
3    E-004     180 pound      81.64656
4    E-005  94 kilograms      94.00000