In [1]:
import pandas as pd 
import numpy as np

In [2]:
df = pd.read_csv('employee_data.csv')
df

,employee_id,name,gender,age,department,position,branch,city,salary,years_experience,performance_score,joining_date,status,email
0,1001,Meron Tadesse,FEMALE,23.0,it,Team Lead,Addis Ababa,Adama,26024.0,18,65.0,25/07/2016,Inactive,meron.tadesse@qiyas.com
1,1002,Abel Bekele,Male,27.0,Operations,Senior Officer,Dire Dawa,Dire Dawa,22328.0,13,64.0,10/1/2021,active,abel.bekele@qiyas.com
2,1003,Bethel Tesfaye,MALE,22.0,Information Technology,Senior Officer,Hawassa,Bahir Dar,18463.0,3,94.0,10/25/2018,Active,bethel.tesfaye@qiyas.com
3,1004,Samuel Tadesse,Male,44.0,Sales,Team Lead,Addis Ababa,Hawassa,30541.0,12,88.0,19/01/2024,Active,samuel.tadesse@qiyas.com
4,1005,Yonas Tesfaye,FEMALE,NaN,Info Tech,Analyst,Addis Ababa,Addis Ababa,45837.0,7,62.0,7/7/2015,Active,yonas.tesfaye@qiyas.com
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198,1199,Nahom Alemu,Male,55.0,Operations,Team Lead,Adama,Hawassa,22486.0,20,76.0,1/2/2018,Inactive,nahom.alemu@qiyas.com
199,1200,Yonas Assefa,female,25.0,HR,Manager,Bahir Dar,Bahir Dar,30571.0,4,91.0,10/24/2023,ACTIVE,yonas.assefa@qiyas.com
200,1021,Liya Tadesse,female,50.0,IT,Junior Officer,Adama,Addis Ababa,44066.0,5,56.0,4/25/2022,Inactive,liya.tadesse@qiyas.com
201,1076,Meron Assefa,female,48.0,Sales,Manager,Addis Ababa,Dire Dawa,11552.0,6,62.0,21/01/2019,ACTIVE,meron.assefa@qiyas.com
202,1121,Eden Alemu,female,26.0,Info Tech,Analyst,Hawassa,Addis Ababa,41455.0,20,90.0,13/12/2020,active,eden.alemu@qiyas.com

In [3]:
df.head(10)

,employee_id,name,gender,age,department,position,branch,city,salary,years_experience,performance_score,joining_date,status,email
0,1001,Meron Tadesse,FEMALE,23.0,it,Team Lead,Addis Ababa,Adama,26024.0,18,65.0,25/07/2016,Inactive,meron.tadesse@qiyas.com
1,1002,Abel Bekele,Male,27.0,Operations,Senior Officer,Dire Dawa,Dire Dawa,22328.0,13,64.0,10/1/2021,active,abel.bekele@qiyas.com
2,1003,Bethel Tesfaye,MALE,22.0,Information Technology,Senior Officer,Hawassa,Bahir Dar,18463.0,3,94.0,10/25/2018,Active,bethel.tesfaye@qiyas.com
3,1004,Samuel Tadesse,Male,44.0,Sales,Team Lead,Addis Ababa,Hawassa,30541.0,12,88.0,19/01/2024,Active,samuel.tadesse@qiyas.com
4,1005,Yonas Tesfaye,FEMALE,NaN,Info Tech,Analyst,Addis Ababa,Addis Ababa,45837.0,7,62.0,7/7/2015,Active,yonas.tesfaye@qiyas.com
5,1006,Samuel Tesfaye,MALE,51.0,Info Tech,Analyst,Addis Ababa,Adama,49660.0,19,73.0,2/25/2019,active,samuel.tesfaye@qiyas.com
6,1007,Yonas Abebe,FEMALE,32.0,Operations,Senior Officer,Hawassa,Hawassa,38294.0,1,74.0,18/05/2025,active,yonas.abebe@qiyas.com
7,1008,Liya Bekele,female,42.0,HR,Senior Officer,Bahir Dar,Addis Ababa,34290.0,12,NaN,5/14/2017,Inactive,liya.bekele@qiyas.com
8,1009,Marta Tesfaye,MALE,30.0,Marketing,Team Lead,Bahir Dar,Dire Dawa,24162.0,11,97.0,1/16/2021,active,marta.tesfaye@qiyas.com
9,1010,Marta Assefa,male,27.0,Marketing,Team Lead,Addis Ababa,Adama,11087.0,12,57.0,14/01/2022,Inactive,marta.assefa@qiyas.com

In [4]:
df.tail(10)

,employee_id,name,gender,age,department,position,branch,city,salary,years_experience,performance_score,joining_date,status,email
193,1194,Eden Alemu,Female,48.0,Marketing,Junior Officer,Dire Dawa,Bahir Dar,32540.0,4,74.0,10/1/2024,ACTIVE,eden.alemu@qiyas.com
194,1195,Sara Alemu,male,56.0,IT,Junior Officer,Hawassa,Adama,33759.0,14,83.0,3/1/2023,Inactive,sara.alemu@qiyas.com
195,1196,Yonas Kebede,MALE,36.0,Info Tech,Junior Officer,Addis Ababa,Hawassa,24220.0,13,79.0,27/09/2016,Active,yonas.kebede@qiyas.com
196,1197,John Abebe,female,26.0,IT,Senior Officer,Addis Ababa,Addis Ababa,14612.0,12,88.0,1/3/2020,Inactive,john.abebe@qiyas.com
197,1198,John Abebe,FEMALE,25.0,HR,Team Lead,Dire Dawa,Hawassa,17183.0,10,82.0,8/17/2017,active,john.abebe@qiyas.com
198,1199,Nahom Alemu,Male,55.0,Operations,Team Lead,Adama,Hawassa,22486.0,20,76.0,1/2/2018,Inactive,nahom.alemu@qiyas.com
199,1200,Yonas Assefa,female,25.0,HR,Manager,Bahir Dar,Bahir Dar,30571.0,4,91.0,10/24/2023,ACTIVE,yonas.assefa@qiyas.com
200,1021,Liya Tadesse,female,50.0,IT,Junior Officer,Adama,Addis Ababa,44066.0,5,56.0,4/25/2022,Inactive,liya.tadesse@qiyas.com
201,1076,Meron Assefa,female,48.0,Sales,Manager,Addis Ababa,Dire Dawa,11552.0,6,62.0,21/01/2019,ACTIVE,meron.assefa@qiyas.com
202,1121,Eden Alemu,female,26.0,Info Tech,Analyst,Hawassa,Addis Ababa,41455.0,20,90.0,13/12/2020,active,eden.alemu@qiyas.com

In [5]:
print(f"Rows: {df.shape[0]}, Columns: {df.shape[1]}")

Rows: 203, Columns: 14

In [6]:
df.dtypes

employee_id            int64
name                  object
gender                object
age                  float64
department            object
position              object
branch                object
city                  object
salary               float64
years_experience       int64
performance_score    float64
joining_date          object
status                object
email                 object
dtype: object

In [7]:
df.describe(include='all')

,employee_id,name,gender,age,department,position,branch,city,salary,years_experience,performance_score,joining_date,status,email
count,203.000000,203,203,201.000000,203,203,203,200,201.000000,203.000000,201.000000,203,203,203
unique,NaN,100,6,NaN,9,5,5,5,NaN,NaN,NaN,196,4,101
top,NaN,Bethel Assefa,female,NaN,Info Tech,Senior Officer,Hawassa,Addis Ababa,NaN,NaN,NaN,11/17/2020,ACTIVE,bethel.assefa@qiyas.com
freq,NaN,5,37,NaN,28,48,46,48,NaN,NaN,NaN,2,58,5
mean,1100.088670,NaN,NaN,40.875622,NaN,NaN,NaN,NaN,31424.164179,10.857143,76.985075,NaN,NaN,NaN
std,57.761733,NaN,NaN,14.551613,NaN,NaN,NaN,NaN,24724.202787,5.886239,14.195942,NaN,NaN,NaN
min,1001.000000,NaN,NaN,-20.000000,NaN,NaN,NaN,NaN,-5000.000000,0.000000,51.000000,NaN,NaN,NaN
25%,1050.500000,NaN,NaN,31.000000,NaN,NaN,NaN,NaN,20439.000000,6.000000,64.000000,NaN,NaN,NaN
50%,1100.000000,NaN,NaN,42.000000,NaN,NaN,NaN,NaN,29708.000000,11.000000,78.000000,NaN,NaN,NaN
75%,1149.500000,NaN,NaN,50.000000,NaN,NaN,NaN,NaN,38743.000000,16.000000,90.000000,NaN,NaN,NaN
max,1200.000000,NaN,NaN,150.000000,NaN,NaN,NaN,NaN,250000.000000,20.000000,120.000000,NaN,NaN,NaN

In [8]:
numerical_cols = df.select_dtypes(include=['int64','float64']).columns.tolist()
print("Numerical Columns", numerical_cols)

Numerical Columns ['employee_id', 'age', 'salary', 'years_experience', 'performance_score']

In [9]:
catagorical_cols = df.select_dtypes(include=['object']).columns.tolist()

In [10]:
print("Catagorical Columns", catagorical_cols)

Catagorical Columns ['name', 'gender', 'department', 'position', 'branch', 'city', 'joining_date', 'status', 'email']

In [11]:
df.isnull()

,employee_id,name,gender,age,department,position,branch,city,salary,years_experience,performance_score,joining_date,status,email
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,True,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198,False,False,False,False,False,False,False,False,False,False,False,False,False,False
199,False,False,False,False,False,False,False,False,False,False,False,False,False,False
200,False,False,False,False,False,False,False,False,False,False,False,False,False,False
201,False,False,False,False,False,False,False,False,False,False,False,False,False,False
202,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [12]:
df.isnull()

,employee_id,name,gender,age,department,position,branch,city,salary,years_experience,performance_score,joining_date,status,email
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,True,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198,False,False,False,False,False,False,False,False,False,False,False,False,False,False
199,False,False,False,False,False,False,False,False,False,False,False,False,False,False
200,False,False,False,False,False,False,False,False,False,False,False,False,False,False
201,False,False,False,False,False,False,False,False,False,False,False,False,False,False
202,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [13]:
df.isnull().sum()

employee_id          0
name                 0
gender               0
age                  2
department           0
position             0
branch               0
city                 3
salary               2
years_experience     0
performance_score    2
joining_date         0
status               0
email                0
dtype: int64

In [14]:
df.columns[df.isnull().any()].tolist()

['age', 'city', 'salary', 'performance_score']

In [15]:

df['age'] = df['age'].fillna(df['age'].mean())

In [16]:

df['city'] = df['city'].fillna(df['city'].mode)

In [17]:

df['salary'] = df['salary'].fillna(df['salary'].mean())

In [18]:

df['performance_score'] = df['performance_score'].fillna(df['performance_score'].mean())

In [19]:
print(df.isnull().sum().sum())

0

In [20]:
duplicates = df[df.duplicated()]
duplicates

,employee_id,name,gender,age,department,position,branch,city,salary,years_experience,performance_score,joining_date,status,email
200,1021,Liya Tadesse,female,50.0,IT,Junior Officer,Adama,Addis Ababa,44066.0,5,56.0,4/25/2022,Inactive,liya.tadesse@qiyas.com
201,1076,Meron Assefa,female,48.0,Sales,Manager,Addis Ababa,Dire Dawa,11552.0,6,62.0,21/01/2019,ACTIVE,meron.assefa@qiyas.com
202,1121,Eden Alemu,female,26.0,Info Tech,Analyst,Hawassa,Addis Ababa,41455.0,20,90.0,13/12/2020,active,eden.alemu@qiyas.com

In [21]:
print(f"Duplicate rows: {df.duplicated().sum()}")

Duplicate rows: 3

In [22]:
df = df.drop_duplicates()

In [23]:
print(df.duplicated().sum())

0

In [24]:
df['gender'] = df['gender'].str.strip().str.title()

C:\Users\kalki\AppData\Local\Temp\ipykernel_86652\1439688053.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['gender'] = df['gender'].str.strip().str.title()

In [25]:
df['department'] = df['department'].str.strip().str.title().replace({
    'It': 'Information Technology',
    'Info Tech': 'Information Technology',
    'Hr': 'Human Resources',
})
print(df['department'])

0      Information Technology
1                  Operations
2      Information Technology
3                       Sales
4      Information Technology
                ...
195    Information Technology
196    Information Technology
197           Human Resources
198                Operations
199           Human Resources
Name: department, Length: 200, dtype: object

C:\Users\kalki\AppData\Local\Temp\ipykernel_86652\1408984199.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['department'] = df['department'].str.strip().str.title().replace({

In [26]:

df['status'] = df['status'].str.strip().str.title()
df['email'] = df['email'].str.strip().str.lower()

C:\Users\kalki\AppData\Local\Temp\ipykernel_86652\2219624367.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['status'] = df['status'].str.strip().str.title()
C:\Users\kalki\AppData\Local\Temp\ipykernel_86652\2219624367.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['email'] = df['email'].str.strip().str.lower()

In [27]:
negative_ages = df[df['age'] < 0]
print(f"Rows with negative ages: {len(negative_ages)}")
if len(negative_ages) > 0:
    print(negative_ages[['employee_id', 'age']])
    df.loc[df['age'] < 0, 'age'] = abs(df.loc[df['age'] < 0, 'age'])

Rows with negative ages: 2
    employee_id   age
14         1015 -20.0
59         1060 -20.0

In [28]:
unrealistic_ages = df[(df['age'] < 18) | (df['age'] > 70)]
print(f"\nRows with unrealistic ages: {len(unrealistic_ages)}")
if len(unrealistic_ages) > 0:
    print(unrealistic_ages[['employee_id', 'age']])
    median_age = df[(df['age'] >= 18) & (df['age'] <= 70)]['age'].median()
    df.loc[(df['age'] < 18) | (df['age'] > 70), 'age'] = median_age

Rows with unrealistic ages: 1
    employee_id    age
89         1090  150.0

In [29]:
negative_salaries = df[df['salary'] < 0]
print(f"\nRows with negative salaries: {len(negative_salaries)}")
if len(negative_salaries) > 0:
    print(negative_salaries[['employee_id', 'salary']])
    df.loc[df['salary'] < 0, 'salary'] = abs(df.loc[df['salary'] < 0, 'salary'])

Rows with negative salaries: 1
    employee_id  salary
24         1025 -5000.0

In [30]:
invalid_scores = df[(df['performance_score'] < 0) | (df['performance_score'] > 100)]
print(f"\nRows with invalid performance scores: {len(invalid_scores)}")
if len(invalid_scores) > 0:
    print(invalid_scores[['employee_id', 'performance_score']])
    df['performance_score'] = df['performance_score'].clip(0, 100)

Rows with invalid performance scores: 1
    employee_id  performance_score
43         1044              120.0

C:\Users\kalki\AppData\Local\Temp\ipykernel_86652\417128498.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['performance_score'] = df['performance_score'].clip(0, 100)

In [31]:
highest_salary = df['salary'].max()
print("highest salary : ",highest_salary)

highest salary :  250000.0

In [32]:
lowest_salary = df['salary'].min()
print("Lowest salary : ", lowest_salary)

Lowest salary :  5000.0

In [33]:
Q1 = df['salary'].quantile(0.25)
Q3 = df['salary'].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
outliers = df[(df['salary'] < lower_bound) | (df['salary'] > upper_bound)] 
outliers

,employee_id,name,gender,age,department,position,branch,city,salary,years_experience,performance_score,joining_date,status,email
69,1070,Samuel Tadesse,Male,56.0,Information Technology,Junior Officer,Addis Ababa,Adama,250000.0,5,91.0,9/3/2025,Active,samuel.tadesse@qiyas.com
179,1180,John Bekele,Male,55.0,Marketing,Analyst,Bahir Dar,Adama,250000.0,3,90.0,8/4/2015,Active,john.bekele@qiyas.com

In [34]:
salary_above = df[df['salary']>100000]
salary_above

,employee_id,name,gender,age,department,position,branch,city,salary,years_experience,performance_score,joining_date,status,email
69,1070,Samuel Tadesse,Male,56.0,Information Technology,Junior Officer,Addis Ababa,Adama,250000.0,5,91.0,9/3/2025,Active,samuel.tadesse@qiyas.com
179,1180,John Bekele,Male,55.0,Marketing,Analyst,Bahir Dar,Adama,250000.0,3,90.0,8/4/2015,Active,john.bekele@qiyas.com

In [35]:
avg_with_outliers = df['salary'].mean()
avg_without_outliers = df[~df.index.isin(outliers.index)]['salary'].mean()

print(f"Average salary with outliers: ${avg_with_outliers:,.2f}")
print(f"Average salary without outliers: ${avg_without_outliers:,.2f}")

Average salary with outliers: $31,460.16
Average salary without outliers: $29,252.69

In [36]:
df['age_group'] = np.where(df['age'] <= 30, 'Young (18-30)',
                  np.where(df['age'] <= 45, 'Mid (31-45)',
                  'Senior (46+)'))

C:\Users\kalki\AppData\Local\Temp\ipykernel_86652\1157651443.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['age_group'] = np.where(df['age'] <= 30, 'Young (18-30)',

In [37]:
print(df[['employee_id', 'name', 'age', 'age_group']].head(10))

   employee_id            name        age      age_group
0         1001   Meron Tadesse  23.000000  Young (18-30)
1         1002     Abel Bekele  27.000000  Young (18-30)
2         1003  Bethel Tesfaye  22.000000  Young (18-30)
3         1004  Samuel Tadesse  44.000000    Mid (31-45)
4         1005   Yonas Tesfaye  40.875622    Mid (31-45)
5         1006  Samuel Tesfaye  51.000000   Senior (46+)
6         1007     Yonas Abebe  32.000000    Mid (31-45)
7         1008     Liya Bekele  42.000000    Mid (31-45)
8         1009   Marta Tesfaye  30.000000  Young (18-30)
9         1010    Marta Assefa  27.000000  Young (18-30)

In [42]:
salary_quantiles = df['salary'].quantile([0.33, 0.67])
print(f"Salary quantiles - 33%: ${salary_quantiles.iloc[0]:,.2f}, 67%: ${salary_quantiles.iloc[1]:,.2f}")

df['salary_category'] = pd.cut(df['salary'],
                               bins=[-float('inf'), salary_quantiles.iloc[0], salary_quantiles.iloc[1], float('inf')],
                               labels=['Low', 'Medium', 'High'])
print(df[['employee_id', 'name', 'salary', 'salary_category', 'years_experience']].head(10))

Salary quantiles - 33%: $23,368.50, 67%: $35,608.25
   employee_id            name   salary salary_category  years_experience
0         1001   Meron Tadesse  26024.0          Medium                18
1         1002     Abel Bekele  22328.0             Low                13
2         1003  Bethel Tesfaye  18463.0             Low                 3
3         1004  Samuel Tadesse  30541.0          Medium                12
4         1005   Yonas Tesfaye  45837.0            High                 7
5         1006  Samuel Tesfaye  49660.0            High                19
6         1007     Yonas Abebe  38294.0            High                 1
7         1008     Liya Bekele  34290.0          Medium                12
8         1009   Marta Tesfaye  24162.0          Medium                11
9         1010    Marta Assefa  11087.0             Low                12

C:\Users\kalki\AppData\Local\Temp\ipykernel_86652\3316076759.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['salary_category'] = pd.cut(df['salary'],

In [43]:
df['experience_level'] = np.where(df['years_experience'] <= 3, 'Junior',
                          np.where(df['years_experience'] <= 7, 'Mid', 'Senior'))
print(df[['employee_id', 'name', 'salary', 'salary_category', 'years_experience', 'experience_level']].head(10))

   employee_id            name   salary salary_category  years_experience  \
0         1001   Meron Tadesse  26024.0          Medium                18
1         1002     Abel Bekele  22328.0             Low                13
2         1003  Bethel Tesfaye  18463.0             Low                 3
3         1004  Samuel Tadesse  30541.0          Medium                12
4         1005   Yonas Tesfaye  45837.0            High                 7
5         1006  Samuel Tesfaye  49660.0            High                19
6         1007     Yonas Abebe  38294.0            High                 1
7         1008     Liya Bekele  34290.0          Medium                12
8         1009   Marta Tesfaye  24162.0          Medium                11
9         1010    Marta Assefa  11087.0             Low                12

  experience_level
0           Senior
1           Senior
2           Junior
3           Senior
4              Mid
5           Senior
6           Junior
7           Senior
8           Senior
9           Senior

C:\Users\kalki\AppData\Local\Temp\ipykernel_86652\4033567551.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['experience_level'] = np.where(df['years_experience'] <= 3, 'Junior',

In [53]:
df['bonus_eligible'] = np.where((df['performance_score'] > 85) & (df['years_experience'] > 3), 'Yes', 'No')
df[df['bonus_eligible'] == 'Yes'][['employee_id', 'name', 'performance_score', 'years_experience', 'bonus_eligible']].head(10)

C:\Users\kalki\AppData\Local\Temp\ipykernel_86652\4091201610.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['bonus_eligible'] = np.where((df['performance_score'] > 85) & (df['years_experience'] > 3), 'Yes', 'No')

,employee_id,name,performance_score,years_experience,bonus_eligible
3,1004,Samuel Tadesse,88.0,12,Yes
8,1009,Marta Tesfaye,97.0,11,Yes
16,1017,Ruth Abebe,95.0,16,Yes
24,1025,Meron Abebe,86.0,13,Yes
27,1028,Marta Assefa,89.0,4,Yes
35,1036,Abel Tadesse,87.0,13,Yes
36,1037,Samuel Abebe,95.0,13,Yes
37,1038,Meron Hailu,96.0,9,Yes
38,1039,John Kebede,89.0,9,Yes
43,1044,Eden Assefa,100.0,7,Yes

In [60]:
total_employees = len(df)
print("Total employees: " ,total_employees)

gender_counts = df['gender'].value_counts()
print(gender_counts)

# Which department has the most employees?
dept_counts = df['department'].value_counts()
print(f"Department with most employees: {dept_counts.index[0]} ({dept_counts.iloc[0]} employees)")
print("All departments: ", dept_counts)

Total employees:  200
gender
Female    102
Male       98
Name: count, dtype: int64
Department with most employees: Information Technology (89 employees)
All departments:  department
Information Technology    89
Human Resources           28
Sales                     22
Marketing                 22
Finance                   20
Operations                19
Name: count, dtype: int64